# This config file for Travis CI utilizes https://github.com/davetcoleman/moveit_ci/ package.
sudo: required
dist: trusty
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    # generate "exotic" locale for parser test
    - BEFORE_SCRIPT="sudo apt-get -qq install -y locales; sudo locale-gen nl_NL.UTF-8"
    - ROS_DISTRO=melodic
    - ROS_REPO=ros
  matrix:
    - TEST="clang-format, catkin_lint"
    - ROS_DISTRO=melodic

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
